# Change this file to look EXACTLY like this:
path: D:/Project/HelmetProject/data/yolo_data  # <--- FIX THIS PATH
train: train/images
val: val/images
test: test/images

names:
  0: motorcycle
  1: rider
  2: license_plate